modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="creeps_crawls"
version="1.0.0"
displayName="Creeps & Crawls"
credits="spage"
displayURL="https://mcreator.net"
authors="spage"

[[dependencies.creeps_crawls]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




